CREATE OR REPLACE VIEW P_LC_ORDER_REVENUE_COST_RECORD AS
(
SELECT
      EXECUTION_DATETIME
    , EXECUTION_DATE
    , LC_BLDG_ID
    , DV_BLDG_ID
    , BLDG_NAME
    , LC_CUST_ID
    , MBR_ID
    , CUST_NAME
    , PHONE_NUM
    , ORDER_LINE_ID
    , LC_PROD_ID
    , DV_PROD_ID
    , PROD_NAME
    , LC_PROMO_ID
    , DV_PROMO_ID
    , PROMO_NAME
    , SUM(ATAX_AMT)                 AS ATAX_AMT
    , QUANTITY
    , WRITE_OFF_QUANTITY
    , TYPE_NAME
    , PROD_TYPE_NAME
    , ACCOUNT_ITEM_TYPE
    , WRITE_OFF_TYPE
    , BILLING_METHOD_GROUPCODE
    , BILLING_TYPE
    , DB
FROM
(
    SELECT
         CASE
            WHEN TO_CHAR(EXECUTION_DATE, 'YYYY-MM-DD') = '1900-01-01' THEN TO_CHAR(DATA_CREATE_DATE,'YYYY-MM-DD HH24:MI:SS')
            ELSE TO_CHAR(EXECUTION_DATE, 'YYYY-MM-DD HH24:MI:SS')
            END AS EXECUTION_DATETIME
        , CASE
            WHEN TO_CHAR(EXECUTION_DATE, 'YYYY-MM-DD') = '1900-01-01' THEN TO_CHAR(DATA_CREATE_DATE,'YYYY-MM-DD')
            ELSE TO_CHAR(EXECUTION_DATE, 'YYYY-MM-DD')
            END AS EXECUTION_DATE
        , OFFICE_ID                     AS LC_BLDG_ID
        , BLDG.BLDG_ID                  AS DV_BLDG_ID
        , BLDG.BLDG_NAME
        , CUSTOMER_ID                   AS LC_CUST_ID
        , CUST.MBR_ID
        , CUST.CUST_NAME
        , CUST.PHONE_NUM
        , ORDER_LINE_ID
        , PRODUCT_ID                    AS LC_PROD_ID
        , PROD.PROD_ID                  AS DV_PROD_ID
        , PROD.PROD_NAME
        , CASE
            WHEN COUPON_PROMOTION_ID = 'NA' THEN NULL
            ELSE COUPON_PROMOTION_ID
            END AS LC_PROMO_ID
        , CASE
            WHEN COUPON_PROMOTION_ID = 'NA' THEN NULL
            ELSE NVL(PROMO.DV_PROMO_ID, regexp_replace(COUPON_PROMOTION_ID, 'j00-', ''))
            END AS DV_PROMO_ID
        , CASE
            WHEN ENVELOPE_NAME = 'NA' THEN NULL
            ELSE ENVELOPE_NAME
            END AS PROMO_NAME
        , AMOUNT AS ATAX_AMT
        , QUANTITY
        , WRITE_OFF_QUANTITY
        , CASE
            WHEN TYPE_NAME = 'NA' THEN NULL
            ELSE TYPE_NAME
            END AS TYPE_NAME
        , CASE
            WHEN PROD_TYPE_NAME = 'NA' THEN NULL
            ELSE PROD_TYPE_NAME
            END AS PROD_TYPE_NAME
        , ACCOUNT_ITEM_TYPE
        , WRITE_OFF_TYPE
        , BILLING_METHOD_GROUPCODE
        , BILLING_TYPE
        , FINA.DB
    FROM DWS_TRD_FINANCIAL_WRITE_OFF_J_IRN_DD FINA
    LEFT JOIN P_LC_BLDG_LOOKUP BLDG ON OFFICE_ID = BLDG.LC_BLDG_ID
    LEFT JOIN P_LC_CUST_LOOKUP CUST ON CUSTOMER_ID = CUST.LC_CUST_ID
    LEFT JOIN P_LC_PROD_LOOKUP PROD ON PRODUCT_ID = PROD.LC_PROD_ID
    LEFT JOIN LC_PROMO_ID_MAPPING PROMO ON COUPON_PROMOTION_ID = PROMO.LC_PROMO_ID
    --WHERE FINA.DB = 'TW'
    --AND BLDG.BLDG_NAME = '竹北DV'
    --AND CUST.CUST_NAME = '姚連霞'
)
GROUP BY
      EXECUTION_DATETIME
    , EXECUTION_DATE
    , LC_BLDG_ID
    , DV_BLDG_ID
    , BLDG_NAME
    , LC_CUST_ID
    , MBR_ID
    , CUST_NAME
    , PHONE_NUM
    , ORDER_LINE_ID
    , LC_PROD_ID
    , DV_PROD_ID
    , PROD_NAME
    , LC_PROMO_ID
    , DV_PROMO_ID
    , PROMO_NAME
    , QUANTITY
    , WRITE_OFF_QUANTITY
    , TYPE_NAME
    , PROD_TYPE_NAME
    , ACCOUNT_ITEM_TYPE
    , WRITE_OFF_TYPE
    , BILLING_METHOD_GROUPCODE
    , BILLING_TYPE
    , DB
)