CREATE OR REPLACE VIEW P_LC_BLDG_LOOKUP AS 
(
SELECT DISTINCT
  ORGANIZATION_ID           AS LC_BLDG_ID 
, ORGANIZATION_NAME         AS BLDG_NAME
, TYPE_NAME                 AS BLDG_TYPE
, ORGANIZATION_LEVEL1_NAME  AS BLDG_L1_NAME
, CASE
    WHEN ORGANIZATION_LEVEL2_NAME = 'NA' THEN NULL
    ELSE ORGANIZATION_LEVEL2_NAME
    END AS  BLDG_L2_NAME
, CASE
    WHEN ORGANIZATION_NAME = '站前DV'		THEN 'AA'
	WHEN ORGANIZATION_NAME = '西門DV'		THEN 'AB'
	WHEN ORGANIZATION_NAME = '忠孝DV'		THEN 'AC'
	WHEN ORGANIZATION_NAME = '桃園DV'		THEN 'AD'
	WHEN ORGANIZATION_NAME = '臺中DV'		THEN 'AE'
	WHEN ORGANIZATION_NAME = '高雄DV'		THEN 'AF'
	WHEN ORGANIZATION_NAME = '信義DV'		THEN 'AG'
	WHEN ORGANIZATION_NAME = '南京DV'		THEN 'AH'
	WHEN ORGANIZATION_NAME = '文心DV'		THEN 'AI'
	WHEN ORGANIZATION_NAME = '竹北DV'		THEN 'AJ'
    
	WHEN ORGANIZATION_NAME = '忠孝診所'		THEN 'JA'
	WHEN ORGANIZATION_NAME = '站前診所'		THEN 'JB'
	WHEN ORGANIZATION_NAME = '西門診所'		THEN 'JC'
	WHEN ORGANIZATION_NAME = '桃園診所'		THEN 'JE'
	WHEN ORGANIZATION_NAME = '臺中診所'		THEN 'JF'
	WHEN ORGANIZATION_NAME = '高雄診所'		THEN 'JG'
	WHEN ORGANIZATION_NAME = '信義診所'		THEN 'JH'
	WHEN ORGANIZATION_NAME = '南京診所'		THEN 'JJ'
	WHEN ORGANIZATION_NAME = '文心診所'		THEN 'JK'
    WHEN ORGANIZATION_NAME = '竹北診所'		THEN 'JL'
    
    WHEN ORGANIZATION_NAME = '翔美診所'		THEN 'K0'
  END AS BLDG_ID
, DB
FROM DIM_ORGANIZATION_IRN_DD
)