CREATE OR REPLACE VIEW P_LC_PROD_LOOKUP AS
(
SELECT  DISTINCT
  UNIQUEKEY             AS LC_PROD_ID
, "NUMBER"              AS PROD_ID
, SKU_NAME              AS PROD_NAME
, SPEC                  AS PROD_SPEC
, UNIT                  AS PROD_UNIT
, TYPE_NAME
, PRODUCT_TYPE_NAME     AS PROD_TYPE_NAME
, CATEGORY_LEVEL1_NAME  AS CATG_NAME_L1
, CATEGORY_LEVEL2_NAME  AS CATG_NAME_L2
, SALE_PRICE            AS SALE_PRICE_AMT
, DB
FROM DIM_SKU_IRN_DD
)