CREATE OR REPLACE VIEW P_LC_ORDERS_PROD AS
(
SELECT
        ITEM.BILLING_OFFICE_ID                      AS LC_BLDG_ID
    ,   BLDG.BLDG_NAME
    ,   BLDG.BLDG_ID
    ,   ITEM.ORDER_ID
    ,   ITEM.ORDER_NUMBER                           AS ORDER_NUM
    ,   CUSTOMER_ID                                 AS LC_CUST_ID
    ,   CUST.CUST_NAME
    ,   ITEM.CONSULTANT_ID                          AS LC_EMPL_ID
    ,   EMPL.EMPL_NAME                              AS CNSLT_EMPL_NAME
    ,   TO_CHAR(ITEM.ORDER_DATE, 'YYYY-MM-DD')      AS ORDER_DATE
    ,   ITEM.PRODUCT_ID                             AS LC_PROD_ID
    ,   PROD.PROD_NAME
    ,   ITEM.COUPON_PROMOTION_ID                    AS LC_PROD_PKG_ID
    ,   ITEM.ORDER_QUANTITY                         AS ORDER_QTY
    ,   ITEM.ACCOUNT_ITEM_TYPE
    ,   ITEM.UNIT_RETAIL_PRICE
    ,   ITEM.UNIT_TRANSACTION_PRICE
    ,   ITEM.DISCOUNT_RATE                          AS DISC_RATE
    , CASE
        WHEN ITEM.ACCOUNT_ITEM_TYPE = '增值金' THEN 0
        ELSE (
            CASE
                WHEN ITEM.REFUND_ORDER_TYPE = '退單' THEN TO_NUMBER(ITEM.UNIT_RETAIL_PRICE) * TO_NUMBER(ITEM.ORDER_QUANTITY) * -1
                ELSE TO_NUMBER(ITEM.UNIT_RETAIL_PRICE) * TO_NUMBER(ITEM.ORDER_QUANTITY) END
            )
        END AS SUB_ORIG_TOTAL_AMT
    , CASE
        WHEN ITEM.ACCOUNT_ITEM_TYPE = '增值金' THEN 0
        ELSE (
            CASE
                WHEN ITEM.REFUND_ORDER_TYPE = '退單' THEN TO_NUMBER(ITEM.UNIT_RETAIL_PRICE) * TO_NUMBER(ITEM.ORDER_QUANTITY) * -1
                ELSE TO_NUMBER(ITEM.UNIT_TRANSACTION_PRICE) * TO_NUMBER(ITEM.ORDER_QUANTITY) END
        )
        END AS SUB_TOTAL_AMT
    , CASE
        WHEN ITEM.ORDER_STATUS = '已廢棄' THEN 0
        ELSE (
            CASE
                WHEN REFUND_ORDER_TYPE = '退單' THEN TO_NUMBER(ITEM.UNIT_RETAIL_PRICE) * TO_NUMBER(ITEM.ORDER_QUANTITY) * -1
                ELSE TO_NUMBER(ITEM.UNIT_TRANSACTION_PRICE) * TO_NUMBER(ITEM.ORDER_QUANTITY) END
        )
        END AS SUB_PAY_AMT
    , ITEM.REFUND_ORDER_TYPE
    , ITEM.ORDER_STATUS
    , ITEM.ORDER_TYPE
    , ITEM.ORIGINAL_ORDER_ID                        AS ORIG_ORDER_ID
    , PROD.CATG_NAME_L1
    , PROD.CATG_NAME_L2
    , PROD.TYPE_NAME
    , PROD.PROD_TYPE_NAME
    , PROD.SALE_PRICE_AMT
    , ITEM.DB
FROM DWS_TRD_ORDER_ITEM_IRN_DD ITEM
LEFT JOIN P_LC_BLDG_LOOKUP BLDG ON ITEM.BILLING_OFFICE_ID = BLDG.LC_BLDG_ID
LEFT JOIN P_LC_CUST_LOOKUP CUST ON ITEM.CUSTOMER_ID = CUST.LC_CUST_ID
LEFT JOIN P_LC_EMPL_LOOKUP EMPL ON ITEM.CONSULTANT_ID = EMPL.LC_EMPL_ID
LEFT JOIN P_LC_PROD_LOOKUP PROD ON ITEM.PRODUCT_ID = PROD.LC_PROD_ID
)