--CREATE OR REPLACE VIEW P_LC_EMPL_LOOKUP AS
(
SELECT  DISTINCT
      LC_EMPL_ID
    , CASE
        WHEN EMPL_NUM = 'NA' THEN NULL
        ELSE EMPL_NUM
        END AS EMPL_NUM
    , CASE
        WHEN EMPL_NAME = 'NA' THEN NULL
        ELSE EMPL_NAME
        END AS EMPL_NAME
    , EMPL_STATUS
    , DB
FROM (
    SELECT
          EMPLOYEE_ID           AS LC_EMPL_ID
        , EMPLOYEE_NUMBER       AS EMPL_NUM
        , EMPLOYEE_NAME         AS EMPL_NAME
        , INSERVICE_STATUS      AS EMPL_STATUS
        , DB
        , ROW_NUMBER() OVER(PARTITION BY EMPLOYEE_ID ORDER BY CREATE_DATE DESC) AS SN
    FROM DIM_EMPLOYEE_IRN_DD
)
WHERE SN = 1
)