CREATE OR REPLACE VIEW P_LC_CUST_LOOKUP AS
(
SELECT
	  CUST.LC_CUST_ID
	, CUST.CUST_NAME
	, CUST.MBR_ID
	, CUST.CUST_STAT
	, CUST.CUST_TYPE
	, CUST.CHNL_TYPE
	, CUST.BIRTH_DATE
	, CUST.SEX
	, CUST.PHONE_NUM
	, CUST.LC_BLDG_ID
	, BLDG.BLDG_NAME
	, BLDG.BLDG_ID
	, CUST.LC_EMPL_ID
	, EMPL.EMPL_NAME 		AS CNSLT_EMPL_NAME
	, CUST.CUST_NOTE
	, CUST.CREATE_DATE
	, CUST.DB
FROM (
	SELECT DISTINCT
		  CUSTOMER_ID 							AS LC_CUST_ID
		, CUSTOMER_NAME 						AS CUST_NAME
		, MEMBERSHIP_NUMBER 					AS MBR_ID
		, CUSTOMER_STATUS 						AS CUST_STAT
		, CUSTOMER_TYPE 						AS CUST_TYPE
		, CHANNEL_TYPE 							AS CHNL_TYPE
		, SUBSTR(CUSTOMER_BIRTHDAY, 1, 10) 		AS BIRTH_DATE
		, GENDER_NAME 							AS SEX
		, PRIMARY_PHONE 						AS PHONE_NUM
		, OFFICE_ID 							AS LC_BLDG_ID
		, CONSULTANT_ID 						AS LC_EMPL_ID
		, CUSTOMER_NOTE 						AS CUST_NOTE
		, TO_CHAR(CREATE_DATE, 'YYYY-MM-DD') 	AS CREATE_DATE
		, DB
		, ROW_NUMBER() OVER(PARTITION BY CUSTOMER_ID ORDER BY CREATE_DATE DESC) AS SN
	FROM DIM_CUSTOMER_IRN_DD
) CUST
LEFT JOIN P_LC_BLDG_LOOKUP BLDG ON CUST.LC_BLDG_ID = BLDG.LC_BLDG_ID
LEFT JOIN P_LC_EMPL_LOOKUP EMPL ON CUST.LC_EMPL_ID = EMPL.LC_EMPL_ID
WHERE SN = 1
AND LC_CUST_ID IS NOT NULL
)